name: tiket_bioskop
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  youtube_player_iframe: ^5.1.2
  http: ^1.2.1
  url_launcher: ^6.3.0
  flutter_local_notifications: ^17.0.0
  flutter_share: ^2.0.0
  screenshot: ^2.0.0
  path_provider: ^2.0.0
  permission_handler: ^10.0.0
  collection: ^1.18.0
  shared_preferences: ^2.2.3  # TAMBAHKAN INI
  local_auth: ^2.1.8  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
